### ISSUE TITLE
Admin Command Help 

### ISSUE THREAD

**Issue by maride** [chaosdorf/telemete#1]
Currently, the `/help` command displays information and usage - but only for commands usable by _normal_ users.

For (new) admins, I'd be helpful to add description and help for the admin-only commands (displayed only if the `admin` flag is set for that specific user).

**Comment by Magluzz** [comment]
Admin help was introduced [here](https://github.com/chaosdorf/telemete/commit/65d4a75da29617d91f0d2782b25f9cc16a93be29url)
