### ISSUE TITLE
deprecation in python-telegram-bot 12

### ISSUE THREAD

**Issue by YtvwlD** [chaosdorf/telemete#12]
Since ec3952f9aeaaf18b250f1c273fa413c65aebcf19, we're using python-telegram-bot 12 and the software prints this message on startup:

```python
run.py:33: TelegramDeprecationWarning: Old Handler API is deprecated - see https://git.io/fxJuV for details
  updater = Updater(token=API_KEY)
```

**Comment by Magluzz** [comment]
This is hotfixed by commit b4dc74b80ebc0f108462f8c420a2b20df9acb0a3

**Comment by YtvwlD** [comment]
Um, well, we can still use version 12. The message is just a warning.

But I'll still try to implement theses changes to be compatible to version 13.
